### ISSUE TITLE
Error "Failed to get dynamic resources. SerdeError(Error("invalid value: string \"v1alpha3\", expected v1", line: 3, column: 25))"

### ISSUE THREAD

**Issue by davidhulick** [kdash-rs/kdash#432]
**Describe the bug**
An error is displayed when opening kdash on a cluster with dynamic resources.

`Failed to get dynamic resources. SerdeError(Error("invalid value: string \"v1alpha3\", expected v1", line: 3, column: 25))`
![2024-01-30_09:31:31](https://github.com/kdash-rs/kdash/assets/6753147/7a173b86-d342-4d1e-bde2-486269d58850)

CRD that causes error:

```
      ---
      apiVersion: cert-manager.io/v1alpha3
      kind: Certificate
      metadata:
        name: ####
        namespace: NAMESPACE
      spec:
        commonName: ####
        dnsNames:
        - cluster.local
        duration: 2160h
        issuerRef:
          name: ca-issuer
        keySize: 2048
        organization:
        - ####
        secretName: ####
        usages:
        - server auth
        - client auth
```

**To Reproduce**
1. open kdash on cluster with certain CRDs
2. error in screenshot above is displayed

**Expected behavior**
Valid dynamic resources are displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and OS version: Fedora 39
 - Terminal name and version: xfce4-terminal 1.1.1
 - Shell name and version: GNU bash, version 5.2.21(1)-release (x86_64-redhat-linux-gnu)
 - Kubectl Client Version 1.28.6
 - Kubectl Server Version 1.26.4
 - KDash version 0.6.0
